### ISSUE TITLE
Doesn't compile on Unity 2018.2.5f1

### ISSUE THREAD

**Issue by aphexetwine** [superunitybuild/buildtool#74]
I get compiler errors on Unity 2018.2.5f1
_Assets/Plugins/buildtool-1.1.0/buildtool-1.1.0/Editor/Build/BuildProject.cs(152,66): error CS1644: Feature `out variable declaration' cannot be used because it is not part of the C# 6.0 language specification_
The highest Scripting Runtime in this version of Unity is 4.x

**Comment by aphexetwine** [comment]
I managed to circumvent the error by fleshing out the inline declarations after `out` as you pointed out. It compiles and works just fine now! Which makes me think, if this is the only reason you are using C# 7.0 then maybe you can still keep support for 2018.x?
In any case, if someone comes across this issue, you have to declare the variables followed by out before the Method call. For example:
`Method(out Class object);`
becomes
```
Class object;
Method(out object);
```

**Comment by robinnorth** [comment]
@aphexetwine that is indeed the correct fix for the issue, I've just released v1.3.0 that includes this.

As for supporting 2018.x, it's more to do with the difference in support for the Assembly Definition files the BuildActions package relies on and finding the time to test against older Unity versions that means I'll drop support for it in v2.0.0. That being said, this current version should work just fine on 2018.x

**Comment by Chaser324** [comment]
Yeah, I will say that one of the biggest challenges in maintainability for any Unity package is the slow incremental changes from version to version, and it being a lot of work to fully regression test in every release. Conditional compile defines can only take you so far.
